version: 2
on:
  pull_request:
    updates:
      - package-ecosystem: "gradle" # See documentation for possible values
      directory: "/" # Location of package manifests
    open-pull-requests-limit: 0